# Generated by Django 4.0.4 on 2022-05-29 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jar3dmodel',
            old_name='name',
            new_name='model_name',
        ),
    ]
