# Generated by Django 4.0.4 on 2022-05-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jar3dmodel',
            name='material',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
